[package]
name = "regex_parser"
version = "0.1.0"
authors = ["yichaolemon <yclemontree0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
hex = "0.4"